### ISSUE TITLE
Max framerate of 50 is too low

### ISSUE THREAD

**Issue by DSteve595** [nostrenz/ffmpeg-video2gif-gui#1]
Nice app!

Currently, the framerate field is limited to 50 FPS. This seems a bit arbitrary, as I've seen 60 FPS gifs work fine. I'd find it helpful to be able to use higher values, particularly 60.

**Comment by nostrenz** [comment]
Unfortunately FFMPEG seems to ignore FPS values above 50. You can try by executing the command line manually and using for example 51 or 60 as the FPS value, the gif will be played in slow-motion.
What could work would be to edit the gif's frame delay after generating it.

**Comment by DSteve595** [comment]
Gotcha, thanks for the info.
